<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SistemaRelatosBugs.Domain\SistemaRelatosBugs.Domain.csproj" />
    <ProjectReference Include="..\SistemaRelatosBugs.Infrastructure\SistemaRelatosBugs.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
