<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SistemaRelatosBugs.Application\SistemaRelatosBugs.Application.csproj" />
    <ProjectReference Include="..\SistemaRelatosBugs.Infrastructure\SistemaRelatosBugs.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
